### ISSUE TITLE
Docker container for easier deployment

### ISSUE THREAD

**Issue by tillig** [Nike-Inc/referee#70]
I could be missing it, but is there a Docker container for Referee? I was hoping to deploy it alongside a Kayenta container and give it a shot but I couldn't find it.

**Comment by StephenWeber** [comment]
There is not one provided in this repo, but this is what we did to build an image to run Referee next to our Kayenta container: https://gist.github.com/StephenWeber/7f24bb22b6448959bf0ec36ac7bcf3c2

I can update it with comments if any steps are not clear why they are being done.

**Comment by melanahammel** [comment]
@StephenWeber Your Dockerfile would be helpful to other developers. Would you be willing to contribute it to the main branch of Referee?

**Comment by tillig** [comment]
So... closed because it's just not going to happen, or...?

**Comment by jiangha4** [comment]
Hello @tillig, thank you for your interest in Referee! A new team is taking over Referee and at the moment, we do not have the capabilities to fulfill this request. I will add a ticket into our backlog to revisit this.
